"""Re-export models from root package for consistency."""

try:
    # Try relative import from parent package
    from ... import (  # noqa: F401
        Base,
        TimestampMixin,
        ActionTimestampMixin,
        generate_uuid,
        # Identity & AI
        AIModel,
        Agent,
        User,
        APIKey,
        # RBAC
        Role,
        Permission,
        RolePermission,
        ActorRoleAssignment,
        BUILT_IN_ROLES,
        # Skills
        SkillDefinition,
        AgentSkill,
        IssueSkillRequirement,
        # Teams
        AssigneeTeam,
        AssigneeTeamMember,
        AgentTeam,
        AgentTeamMember,
        # Projects
        Project,
        Label,
        ProjectMetadata,
        DataClassification,
        # Issues
        Issue,
        IssueLabel,
        IssueLink,
        IssueAssignment,
        IssueWatcher,
        IssueInstruction,
        InstructionCompletion,
        IssueTemplate,
        # Sprints
        Sprint,
        SprintIssue,
        SprintGoal,
        SprintCapacity,
        BurndownSnapshot,
        Ceremony,
        StandupRecord,
        StandupItem,
        # Quality
        DefinitionOfReady,
        DefinitionOfDone,
        DORCheck,
        DODCheck,
        Review,
        ReviewCriterion,
        # Workflow
        StatusTransition,
        Handover,
        Impediment,
        Workflow,
        WorkflowStep,
        WorkflowRun,
        # Regulatory
        ComplianceCheck,
        ApprovalWorkflow,
        ApprovalRequest,
        AccessLog,
        # Agent ops
        AgentAvailability,
        TaskQueue,
        ExecutionLog,
        AgentFeedback,
        AgentLog,
        AgentMessage,
        AgentTokenUsage,
        AgentTokenBudget,
        TokenBudgetAlert,
        # Memory & compression
        ProjectMemory,
        ContextCompressionRule,
        ContextSnapshot,
        ContentEmbedding,
        # History
        IssueChangeLog,
        Note,
        VelocityRecord,
        TimeEntry,
        # Deliverables
        Deliverable,
        DeliverableStatusHistory,
        DeliverableDistribution,
        DeliverableDependency,
        ExpectedDeliverable,
        # Reports
        ReportDefinition,
        ReportInstance,
        ReportSchedule,
        # Notifications
        NotificationRule,
        NotificationTemplate,
        Notification,
        # Knowledge
        WikiPage,
        WikiPageVersion,
        Attachment,
        # Contacts
        UserContact,
        TelegramCommand,
        # Jobs
        BackgroundJob,
        # Prompts
        PromptTemplate,
        PromptVersion,
        PromptFragment,
        # Analytics
        ModelPerformance,
    )
except ImportError as e:
    raise ImportError(
        "Failed to import models from root package. "
        "Ensure the root __init__.py is properly configured."
    ) from e

__all__ = [
    "Base",
    "TimestampMixin",
    "ActionTimestampMixin",
    "generate_uuid",
    "AIModel",
    "Agent",
    "User",
    "APIKey",
    "Role",
    "Permission",
    "RolePermission",
    "ActorRoleAssignment",
    "BUILT_IN_ROLES",
    "SkillDefinition",
    "AgentSkill",
    "IssueSkillRequirement",
    "AssigneeTeam",
    "AssigneeTeamMember",
    "AgentTeam",
    "AgentTeamMember",
    "Project",
    "Label",
    "ProjectMetadata",
    "DataClassification",
    "Issue",
    "IssueLabel",
    "IssueLink",
    "IssueAssignment",
    "IssueWatcher",
    "IssueInstruction",
    "InstructionCompletion",
    "IssueTemplate",
    "Sprint",
    "SprintIssue",
    "SprintGoal",
    "SprintCapacity",
    "BurndownSnapshot",
    "Ceremony",
    "StandupRecord",
    "StandupItem",
    "DefinitionOfReady",
    "DefinitionOfDone",
    "DORCheck",
    "DODCheck",
    "Review",
    "ReviewCriterion",
    "StatusTransition",
    "Handover",
    "Impediment",
    "Workflow",
    "WorkflowStep",
    "WorkflowRun",
    "ComplianceCheck",
    "ApprovalWorkflow",
    "ApprovalRequest",
    "AccessLog",
    "AgentAvailability",
    "TaskQueue",
    "ExecutionLog",
    "AgentFeedback",
    "AgentLog",
    "AgentMessage",
    "AgentTokenUsage",
    "AgentTokenBudget",
    "TokenBudgetAlert",
    "ProjectMemory",
    "ContextCompressionRule",
    "ContextSnapshot",
    "ContentEmbedding",
    "IssueChangeLog",
    "Note",
    "VelocityRecord",
    "TimeEntry",
    "Deliverable",
    "DeliverableStatusHistory",
    "DeliverableDistribution",
    "DeliverableDependency",
    "ExpectedDeliverable",
    "ReportDefinition",
    "ReportInstance",
    "ReportSchedule",
    "NotificationRule",
    "NotificationTemplate",
    "Notification",
    "WikiPage",
    "WikiPageVersion",
    "Attachment",
    "UserContact",
    "TelegramCommand",
    "BackgroundJob",
    "PromptTemplate",
    "PromptVersion",
    "PromptFragment",
    "ModelPerformance",
]
