"""
Issues — the atomic unit of work.

Self-referential parent_issue_id enables the hierarchy:
  Epic (issue_type='epic') → Story → Task → Subtask

Epics are issues with issue_type='epic' and parent_issue_id=NULL.
The separate epics table has been removed in favor of this unified model.
"""
from __future__ import annotations
from datetime import datetime
from typing import Optional
from sqlalchemy import (
    Boolean, DateTime, Float, ForeignKey, Integer, String, Text, func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

try:
    from .base import Base, TimestampMixin, generate_uuid
except ImportError:
    from base import Base, TimestampMixin, generate_uuid


class Issue(Base, TimestampMixin):
    __tablename__ = "issues"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)

    # Hierarchy
    project_id: Mapped[str] = mapped_column(String(36), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True)
    parent_issue_id: Mapped[Optional[str]] = mapped_column(String(36), ForeignKey("issues.id"), nullable=True, index=True)
    sprint_id: Mapped[Optional[str]] = mapped_column(String(36), ForeignKey("sprints.id"), nullable=True, index=True)
    epic_id: Mapped[Optional[str]] = mapped_column(String(36), ForeignKey("issues.id"), nullable=True, index=True)
    # Convenience FK: points to the root epic even for deeply nested issues

    # Classification
    issue_type: Mapped[str] = mapped_column(String(20), default="task", nullable=False)
    # 'epic' | 'story' | 'task' | 'subtask' | 'bug' | 'feature' |
    # 'spike' | 'chore' | 'regulatory' | 'safety_analysis'

    # Identity
    issue_number: Mapped[Optional[int]] = mapped_column(Integer, nullable=True, index=True)
    # Auto-incremented per project: PROJ-001, PROJ-002
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    description_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # Auto-generated by compression agent (≤60 tokens)

    # Status & Priority
    status: Mapped[str] = mapped_column(String(30), default="backlog", nullable=False, index=True)
    # 'backlog' | 'ready' | 'in_progress' | 'in_review' | 'blocked' |
    # 'done' | 'cancelled' | 'deferred'
    priority: Mapped[str] = mapped_column(String(20), default="medium", nullable=False, index=True)
    # 'critical' | 'high' | 'medium' | 'low'
    importance: Mapped[str] = mapped_column(String(20), default="medium", nullable=False)
    # 'critical' | 'high' | 'medium' | 'low'
    difficulty: Mapped[str] = mapped_column(String(20), default="medium", nullable=False)
    # 'trivial' | 'easy' | 'medium' | 'hard' | 'very_hard' | 'research'

    # Estimation
    story_points: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    # Fibonacci: 1 2 3 5 8 13 21
    progress_pct: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    # 0-100

    # Backlog ordering
    backlog_rank: Mapped[Optional[float]] = mapped_column(
        Float, nullable=True, index=True,
        comment="Fractional ordering key for backlog prioritization. Lower = higher priority."
    )

    # Assignment
    assignee_id: Mapped[Optional[str]] = mapped_column(String(36), nullable=True, index=True)
    assignee_type: Mapped[Optional[str]] = mapped_column(String(10), nullable=True)
    # 'user' | 'agent'
    assignee_team_id: Mapped[Optional[str]] = mapped_column(String(36), ForeignKey("assignee_teams.id"), nullable=True)

    # Ownership
    created_by_id: Mapped[str] = mapped_column(String(36), nullable=False)
    created_by_type: Mapped[str] = mapped_column(String(10), nullable=False, default="user")

    # Dates
    due_date: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    started_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    # Formal / regulatory
    classification_id: Mapped[Optional[str]] = mapped_column(String(36), ForeignKey("data_classifications.id"), nullable=True)
    external_ref: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
    # Reference to external system (JIRA, requirement ID, etc.)

    # DoR / DoD gating
    dor_passed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    dod_passed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Self-referential relationships
    parent: Mapped[Optional["Issue"]] = relationship("Issue", remote_side="Issue.id", foreign_keys=[parent_issue_id], back_populates="children")
    children: Mapped[list["Issue"]] = relationship("Issue", foreign_keys=[parent_issue_id], back_populates="parent")

    # Related entities
    project: Mapped["Project"] = relationship("Project", back_populates="issues")
    assignee_team: Mapped[Optional["AssigneeTeam"]] = relationship("AssigneeTeam")
    labels: Mapped[list["IssueLabel"]] = relationship("IssueLabel", back_populates="issue")
    links: Mapped[list["IssueLink"]] = relationship("IssueLink", back_populates="source_issue", foreign_keys="IssueLink.source_id")
    assignments: Mapped[list["IssueAssignment"]] = relationship("IssueAssignment", back_populates="issue")
    watchers: Mapped[list["IssueWatcher"]] = relationship("IssueWatcher", back_populates="issue")
    instructions: Mapped[list["IssueInstruction"]] = relationship("IssueInstruction", back_populates="issue", order_by="IssueInstruction.order_index")
    skill_requirements: Mapped[list["IssueSkillRequirement"]] = relationship("IssueSkillRequirement")
    change_log: Mapped[list["IssueChangeLog"]] = relationship("IssueChangeLog", back_populates="issue")
    status_transitions: Mapped[list["StatusTransition"]] = relationship("StatusTransition", back_populates="issue")
    # notes relationship removed until models are complete
    # deliverables relationship removed until models are complete
    # execution_logs relationship removed until models are complete
    # TODO: Restore these relationships when models are fully implemented

    def __repr__(self) -> str:
        return f"<Issue {self.issue_type.upper()} '{self.title[:40]}' [{self.status}]>"


class IssueLabel(Base):
    __tablename__ = "issue_labels"
    issue_id: Mapped[str] = mapped_column(String(36), ForeignKey("issues.id", ondelete="CASCADE"), primary_key=True)
    label_id: Mapped[str] = mapped_column(String(36), ForeignKey("labels.id", ondelete="CASCADE"), primary_key=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)
    issue: Mapped["Issue"] = relationship("Issue", back_populates="labels")
    label: Mapped["Label"] = relationship("Label")


class IssueLink(Base, TimestampMixin):
    __tablename__ = "issue_links"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    source_id: Mapped[str] = mapped_column(String(36), ForeignKey("issues.id", ondelete="CASCADE"), nullable=False, index=True)
    target_id: Mapped[str] = mapped_column(String(36), ForeignKey("issues.id", ondelete="CASCADE"), nullable=False, index=True)
    link_type: Mapped[str] = mapped_column(String(20), nullable=False)
    # 'blocks' | 'is_blocked_by' | 'relates_to' | 'duplicates' | 'requires'
    created_by_id: Mapped[str] = mapped_column(String(36), nullable=False)
    source_issue: Mapped["Issue"] = relationship("Issue", back_populates="links", foreign_keys=[source_id])
    target_issue: Mapped["Issue"] = relationship("Issue", foreign_keys=[target_id])


class IssueAssignment(Base, TimestampMixin):
    __tablename__ = "issue_assignments"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    issue_id: Mapped[str] = mapped_column(String(36), ForeignKey("issues.id", ondelete="CASCADE"), nullable=False, index=True)
    actor_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    actor_type: Mapped[str] = mapped_column(String(10), nullable=False)
    role: Mapped[str] = mapped_column(String(20), default="primary", nullable=False)
    # 'primary' | 'reviewer' | 'observer'
    assigned_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)
    accepted_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    issue: Mapped["Issue"] = relationship("Issue", back_populates="assignments")


class IssueWatcher(Base):
    __tablename__ = "issue_watchers"
    issue_id: Mapped[str] = mapped_column(String(36), ForeignKey("issues.id", ondelete="CASCADE"), primary_key=True)
    actor_id: Mapped[str] = mapped_column(String(36), primary_key=True)
    actor_type: Mapped[str] = mapped_column(String(10), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)
    issue: Mapped["Issue"] = relationship("Issue", back_populates="watchers")


class IssueInstruction(Base, TimestampMixin):
    """
    Specific, actionable directive for working on THIS issue.
    Read by agents before execution. Enforced by the Gateway for 'must' priority.
    """
    __tablename__ = "issue_instructions"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    issue_id: Mapped[str] = mapped_column(String(36), ForeignKey("issues.id", ondelete="CASCADE"), nullable=False, index=True)
    instruction_type: Mapped[str] = mapped_column(String(20), nullable=False)
    # 'approach' | 'constraint' | 'sequence' | 'reference' |
    # 'compliance' | 'warning' | 'context'
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    priority: Mapped[str] = mapped_column(String(10), default="should", nullable=False)
    # 'must' | 'should' | 'could'   (MoSCoW)
    target_actor_type: Mapped[str] = mapped_column(String(10), default="any", nullable=False)
    # 'any' | 'human' | 'agent' | 'reviewer'
    order_index: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    reference_url: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True)
    authored_by_id: Mapped[str] = mapped_column(String(36), nullable=False)
    authored_by_type: Mapped[str] = mapped_column(String(10), nullable=False, default="user")
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    issue: Mapped["Issue"] = relationship("Issue", back_populates="instructions")
    completions: Mapped[list["InstructionCompletion"]] = relationship("InstructionCompletion", back_populates="instruction")
    def __repr__(self) -> str: return f"<Instruction [{self.priority}] {self.title[:40]}>"


class InstructionCompletion(Base):
    __tablename__ = "instruction_completions"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    instruction_id: Mapped[str] = mapped_column(String(36), ForeignKey("issue_instructions.id", ondelete="CASCADE"), nullable=False, index=True)
    actor_id: Mapped[str] = mapped_column(String(36), nullable=False)
    actor_type: Mapped[str] = mapped_column(String(10), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False)
    # 'acknowledged' | 'completed' | 'skipped' | 'blocked' | 'not_applicable'
    completion_note: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=func.now(), nullable=False)
    instruction: Mapped["IssueInstruction"] = relationship("IssueInstruction", back_populates="completions")


class IssueTemplate(Base, TimestampMixin):
    __tablename__ = "issue_templates"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    name: Mapped[str] = mapped_column(String(150), nullable=False)
    issue_type: Mapped[str] = mapped_column(String(20), nullable=False)
    project_id: Mapped[Optional[str]] = mapped_column(String(36), ForeignKey("projects.id"), nullable=True)
    default_title: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    default_description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    default_priority: Mapped[str] = mapped_column(String(20), default="medium", nullable=False)
    default_difficulty: Mapped[str] = mapped_column(String(20), default="medium", nullable=False)
    default_skill_requirements_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    checklist_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_by_id: Mapped[str] = mapped_column(String(36), nullable=False)


